#!/usr/bin/env bash
# ------------------------------------------------------------------
# Backup GitLab (Omnibus) Configuration
# ------------------------------------------------------------------

# Text Colors
COLOR_FAIL="\033[31m"
COLOR_PASS="\033[36m"
COLOR_BOLD="\033[1m"
COLOR_RESET="\033[m"

# Config
APP_NAME="gitlab-config-backup"
APP_VERSION="0.0.1"
GITLAB_CONFIG_PATH="/etc/gitlab"
GITLAB_BACKUP_PATH="/var/backups/gitlab"

BACKUP_BASE_NAME="_gitlab-omnibus-config.tar.gz"
BACKUP_TIMESTAMP=$(date -u +%s)
BACKUP_NAME="$BACKUP_TIMESTAMP$BACKUP_BASE_NAME"
#
# First check for the GitLab Config Folder
#
if [[ ! -d "$GITLAB_CONFIG_PATH" ]]; then
    echo -e $COLOR_FAIL"GitLab config folder could not be found:"$COLOR_RESET$COLOR_PASS $GITLAB_CONFIG_PATH
    exit -1
fi

if [[ ! -d "$GITLAB_BACKUP_PATH" ]]; then
    mkdir -p "$GITLAB_BACKUP_PATH"
    echo -e $COLOR_PASS"Backup folder created..."$COLOR_RESET
    echo -e "  -> $GITLAB_BACKUP_PATH/"
fi

# Archive the config folder
$(cd "$GITLAB_BACKUP_PATH"; tar -zcvf "$BACKUP_NAME" .)

if [[ -f "$GITLAB_BACKUP_PATH/$BACKUP_NAME" ]]; then
    echo -e $COLOR_PASS"Backup of GitLab configuration completed..."$COLOR_RESET
    echo -e "  -> $GITLAB_BACKUP_PATH/$BACKUP_NAME"
    exit 0
else
    echo -e $COLOR_FAIL"Backup of GitLab configuration FAILED..."$COLOR_RESET
    exit 1
fi
